// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Samples.Database.Scripts.PostDeployment
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Users\AEvlampiev\source\repos\AlexeyEvlampiev\Solitons.Core\samples\Solitons.Samples.Database\Scripts\PostDeployment\RegisterSuperuser.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RegisterSuperuser : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("INSERT INTO system.user(id) VALUES ");
            
            #line 6 "D:\Users\AEvlampiev\source\repos\AlexeyEvlampiev\Solitons.Core\samples\Solitons.Samples.Database\Scripts\PostDeployment\RegisterSuperuser.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EmailValues));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
