// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Samples.Database.Scripts.PostDeployment
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RegisterSuperuserRtt : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("INSERT INTO system.user(email, organization_object_id) VALUES ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ValuesCsv));
            this.Write("\r\nON CONFLICT(email) DO UPDATE SET \r\n\torganization_object_id = EXCLUDED.organizat" +
                    "ion_object_id;");
            return this.GenerationEnvironment.ToString();
        }
    }
}
