// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Data.Common.Postgres
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CommonPgScriptRtt : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nCREATE DOMAIN ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(".natural_key AS varchar(150) CHECK(VALUE ~ \'^\\S.*\\S$\');\r\nCREATE DOMAIN ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(".version AS varchar(25) CHECK (value ~ \'^\\d+(\\.\\d+){0,3}$\');\r\nCREATE DOMAIN ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(".email AS varchar(150) CHECK ( value ~ \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(EmailPattern));
            this.Write("\');\r\n\r\nCREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(@".raise_exception_if_null_argument(arg anyelement, arg_name varchar(50)) RETURNS void AS
$$
BEGIN
	IF arg IS NULL THEN
		RAISE EXCEPTION '''%'' argument is required', COALESCE(arg_name, '?');
	END IF;
END;
$$ LANGUAGE 'plpgsql' IMMUTABLE;



CREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(@".raise_exception_if_null_or_empty_argument(arg uuid, arg_name varchar(50)) RETURNS void AS
$$
BEGIN
	IF NULLIF(arg, '00000000-0000-0000-0000-000000000000'::uuid) IS NULL THEN
		RAISE EXCEPTION '''%'' argument is required', COALESCE(arg_name, '?');
	END IF;
END;
$$ LANGUAGE 'plpgsql' IMMUTABLE;

CREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(@".raise_exception_if_empty_argument(arg uuid, arg_name varchar(50)) RETURNS void AS
$$
BEGIN
	IF arg = '00000000-0000-0000-0000-000000000000'::uuid THEN
		RAISE EXCEPTION '''%'' argument is empty.', COALESCE(arg_name, '?');
	END IF;
END;
$$ LANGUAGE 'plpgsql' IMMUTABLE;



CREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(@".raise_exception_if_null_or_empty_argument(arg text, arg_name varchar(50)) RETURNS void AS
$$
BEGIN
	IF NULLIF(TRIM(arg), '') IS NULL THEN
		RAISE EXCEPTION '''%'' argument is required', COALESCE(arg_name, '?');
	END IF;
END;
$$ LANGUAGE 'plpgsql' IMMUTABLE;



CREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(@".try_cast(_in text, INOUT _out ANYELEMENT) AS
$$
BEGIN
   EXECUTE FORMAT('SELECT %L::%s', $1, pg_typeof(_out)) INTO  _out;
EXCEPTION WHEN others THEN
   -- do nothing: _out already carries default
END;
$$ LANGUAGE 'plpgsql' IMMUTABLE;



CREATE OR REPLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(".nullif_empty(_arg uuid) RETURNS uuid AS\r\n$$\r\n\tSELECT NULLIF(_arg, \'00000000-0000" +
                    "-0000-0000-000000000000\'::uuid);\r\n$$ LANGUAGE \'sql\' IMMUTABLE;\r\n\r\n\r\nCREATE OR RE" +
                    "PLACE FUNCTION ");
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaName));
            this.Write(".is_empty(_arg uuid) RETURNS bool AS\r\n$$\r\n\tSELECT (_arg = \'00000000-0000-0000-000" +
                    "0-000000000000\'::uuid);\r\n$$ LANGUAGE \'sql\' IMMUTABLE;");
            return this.GenerationEnvironment.ToString();
        }
    }
}
