// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Data.Postgres
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CreateDbScriptRtt : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
 if(DatabaseExists){ 
            this.Write(" \r\nALTER DATABASE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            this.Write(" OWNER TO ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseAdmin));
            this.Write(";\r\n\r\n");
 } else { 
            this.Write(" \r\nCREATE DATABASE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            this.Write(" WITH OWNER ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseAdmin));
            this.Write(";\r\n");
 } 
            this.Write("  \r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
