// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Security.Postgres.Scripts
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CreatePgDatabaseScriptRtt : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\r\nDO\r\n$$\r\nBEGIN\r\n   IF EXISTS (SELECT FROM pg_database WHERE datname = \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            this.Write("\') THEN\r\n      ALTER DATABASE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            this.Write(" OWNER TO ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseAdmin));
            this.Write(";\r\n   ELSE\r\n      CREATE DATABASE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            this.Write(" WITH OWNER ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseAdmin));
            this.Write(";\r\n   END IF;\r\nEND\r\n$$;\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
