// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Security.Postgres.Scripts
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CreatePgRolesScriptRtt : Solitons.Text.Sql.PgRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("DO\r\n$$\r\nBEGIN\r\n\tIF EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE  rolname = \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write("\') THEN\r\n\t\tALTER ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write(" WITH\r\n\t\t\tLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS\r\n" +
                    "\t\t\tCONNECTION LIMIT 10;\r\n\tELSE\r\n\t\tCREATE ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write(" WITH\r\n\t\t\tLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS\r\n" +
                    "\t\t\tPASSWORD NULL\r\n\t\t\tCONNECTION LIMIT 10;\r\n\tEND IF;\r\n\r\n\tGRANT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write(" TO current_user;\r\nEND;\r\n$$;\r\n\r\n\r\n");
 foreach(var role in RolesWithLogin ){ 
            this.Write(" \r\n\r\nDO\r\n$$\r\nBEGIN\r\n\tIF EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE  rolname =" +
                    " \'");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write("\') THEN\r\n\t\tALTER ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" WITH\r\n\t\t\tLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS\r\n" +
                    "\t\t\tCONNECTION LIMIT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(role.ConnectionLimit));
            this.Write(";\r\n\tELSE\r\n\t\tCREATE ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" WITH\r\n\t\t\tLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS\r\n" +
                    "\t\t\tPASSWORD NULL\r\n\t\t\tCONNECTION LIMIT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(role.ConnectionLimit));
            this.Write(";\r\n\tEND IF;\r\n\r\n\tGRANT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" TO ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write(";\r\nEND;\r\n$$;\r\n");
 } 
            this.Write(" \r\n\r\n");
 foreach(var role in RouleGroups ){ 
            this.Write(" \r\nDO\r\n$$\r\nBEGIN\r\n\tIF EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE  rolname = \'" +
                    "");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write("\') THEN\r\n\t\tALTER ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" WITH\r\n\t\t\tNOLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS" +
                    ";\r\n\tELSE\r\n\t\tCREATE ROLE ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" WITH\r\n\t\t\tNOLOGIN\r\n\t\t\tNOINHERIT\r\n\t\t\tNOSUPERUSER\r\n\t\t\tNOREPLICATION\r\n\t\t\tNOBYPASSRLS" +
                    ";\r\n\tEND IF;\r\n\r\n\tGRANT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" TO ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName("admin")));
            this.Write("; ");
 foreach(var login in GetLoginMembers(role)){ 
            this.Write(" \r\n\tGRANT ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(role.Name)));
            this.Write(" TO ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRoleFullName(login.Name)));
            this.Write(";\r\n\t");
 } 
            this.Write(" \r\nEND;\r\n$$;\r\n\r\n");
 } 
            this.Write(" \r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
