// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Text.Json
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AutoCorrectedJsonTemplate : JsonRuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("{\r\n\t\"property1\": 123\r\n\t\"property2\": \"Hello world!\"\r\n\t\"myArray\":[1, 2, 3,]\r\n\t\"myMa" +
                    "p\":{\r\n\t\t\"a\": true,\r\n\t\t\"b\": false,\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
