name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache DocFx tools
      uses: actions/cache@v2
      with:
        path: ~/.dotnet/tools
        key: docfx-${{ hashFiles('**/docfx.json') }}
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Build Project
      run: dotnet build ./src/Solitons.Core/Solitons.Core.csproj --configuration Release        
    - name: Update DocFx
      run: dotnet tool update -g docfx
    - name: Generate Docs
      run: docfx docfx_project/docfx.json
    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli
    - name: Upload to Azure Blob
      env: 
        AZ_STORAGE_SOLITONS_ACCOUNT_KEY: ${{secrets.AZ_STORAGE_SOLITONS_ACCOUNT_KEY}}
      run: |
        az storage blob upload-batch \
        --destination '$web' \
        --source docfx_project/_site \
        --account-key ${{env.AZ_STORAGE_SOLITONS_ACCOUNT_KEY}} \
        --account-name solitons      
        
