name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x']
    env:
     projectpath: ./src/Solitons.Core/Solitons.Core.csproj
     buildconfiguration: release
     outputpath: pkgout
     runId: ${{github.run_id}}
     nugetsource: https://api.nuget.org/v3/index.json
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${buildconfiguration}
    - name: Test
      env:
       AZ_STORAGE_CONNECTION_STRING: ${{secrets.AZ_STORAGE_CONNECTION_STRING}}
      run: dotnet test --no-build --verbosity normal   
    - name: Pack
      env:
       versionsuffix: 'alpha.${{env.runId}}'
      run: dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --version-suffix ${versionsuffix} --no-build --no-restore
    - name: Push
      env:
       NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push ${outputpath}/*.nupkg --api-key ${NUGET_API_KEY} --source ${nugetsource} --skip-duplicate

     
