name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
     projectpath: ./src/Solitons.Core/Solitons.Core.csproj
     buildconfiguration: release
     outputpath: pkgout
     runId: ${{github.run_id}}
     nugetsource: https://api.nuget.org/v3/index.json
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x        
    - name: Restore dependencies
      run: dotnet restore Solitons.Core.sln
    - name: Build
      run: dotnet build Solitons.Core.sln --no-restore --configuration ${buildconfiguration}
    - name: Test
      env:
       AZ_STORAGE_CONNECTION_STRING: ${{secrets.AZ_STORAGE_CONNECTION_STRING}}
      run: dotnet test Solitons.Core.sln --no-build --verbosity normal   
    - name: Pack
      env:
       versionsuffix: 'alpha.${{env.runId}}'
      run: dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --version-suffix ${versionsuffix} --no-build --no-restore
    - name: Push
      env:
       NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push ${outputpath}/*.nupkg --api-key ${NUGET_API_KEY} --source ${nugetsource} --skip-duplicate

     
